services:
  mysql:
    image: mysql:8
    container_name: mysql_estudiantes
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: estudiantes_db
    ports:
      - "3306:3306"
    restart: always

  api:
    build: .
    container_name: api_estudiantes
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/estudiantes_db
      DB_USER: root
      DB_PASS: ""
    restart: always